In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [2]:


crop = pd.read_csv("crop_production.csv")

In [4]:
crop.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [5]:
crop.info()

<class 'pandas.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  str
 1   District_Name  246091 non-null  str
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  str
 4   Crop           246091 non-null  str
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.1 MB

In [6]:
crop = crop.dropna(subset=["Production"])

In [7]:
print(crop.columns)

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='str')

In [8]:
crop = crop.rename(columns={
    "State_Name": "state",
    "Crop_Year": "year"
})

In [14]:
print(crop.columns)

Index(['state', 'District_Name', 'year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

In [9]:
crop = crop.drop(columns=["District_Name"])

In [10]:
print(crop["state"].unique()[:20])

<StringArray>
['Andaman and Nicobar Islands',              'Andhra Pradesh',
           'Arunachal Pradesh',                       'Assam',
                       'Bihar',                  'Chandigarh',
                'Chhattisgarh',      'Dadra and Nagar Haveli',
                         'Goa',                     'Gujarat',
                     'Haryana',            'Himachal Pradesh',
          'Jammu and Kashmir ',                   'Jharkhand',
                   'Karnataka',                      'Kerala',
              'Madhya Pradesh',                 'Maharashtra',
                     'Manipur',                   'Meghalaya']
Length: 20, dtype: str

In [11]:
state_mapping = {
    "Assam": "ASSAM & MEGHALAYA",
    "Meghalaya": "ASSAM & MEGHALAYA",
    "Jharkhand": "JHARKHAND",
    "Bihar": "BIHAR",
    "Arunachal Pradesh": "ARUNACHAL PRADESH",
    "Andaman and Nicobar Islands": "ANDAMAN & NICOBAR ISLANDS"
}

In [12]:
crop["rainfall_state"] = crop["state"].map(state_mapping)

In [13]:
left_on=["rainfall_state", "year"]
right_on=["state", "year"]

In [14]:
sorted(crop["state"].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir ',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana ',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [15]:
rainfall = pd.read_csv("rainfall_cleaned.csv")

In [16]:
print(rainfall.head())

   year  rainfall                        state
0  1901    3373.2  Andaman and Nicobar Islands
1  1902    3520.7  Andaman and Nicobar Islands
2  1903    2957.4  Andaman and Nicobar Islands
3  1904    3079.6  Andaman and Nicobar Islands
4  1905    2566.7  Andaman and Nicobar Islands

In [18]:
print(rainfall.columns)

Index(['year', 'rainfall', 'state'], dtype='str')

In [19]:
crop = crop.rename(columns={
    "State_Name": "state",
    "Crop_Year": "year"
})

In [20]:
crop["state"] = crop["state"].str.strip()
rainfall["state"] = rainfall["state"].str.strip()

In [21]:
common_states = set(crop["state"].unique()) & set(rainfall["state"].unique())

print("Matching states:", len(common_states))
print(sorted(common_states))

Matching states: 31
['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [22]:
print(crop.columns)

Index(['state', 'year', 'Season', 'Crop', 'Area', 'Production',
       'rainfall_state'],
      dtype='str')

In [23]:
print(rainfall.columns)

Index(['year', 'rainfall', 'state'], dtype='str')

In [24]:
crop.columns = crop.columns.str.strip()
rainfall.columns = rainfall.columns.str.strip()

In [25]:
crop = crop.drop(columns=["rainfall_state"], errors="ignore")

In [26]:
crop["state"] = crop["state"].str.strip()
rainfall["state"] = rainfall["state"].str.strip()

In [27]:
df = pd.merge(
    crop,
    rainfall,
    on=["state", "year"],
    how="left"
)

In [28]:
df.isnull().sum()

state            0
year             0
Season           0
Crop             0
Area             0
Production       0
rainfall      1135
dtype: int64

In [29]:
print(crop["year"].min(), crop["year"].max())
print(rainfall["year"].min(), rainfall["year"].max())

1997 2015
1901 2015

In [30]:
df = df[df["year"] >= 1997]

In [31]:
df.isnull().sum()

state            0
year             0
Season           0
Crop             0
Area             0
Production       0
rainfall      1135
dtype: int64

In [32]:
df[df["rainfall"].isna()][["state", "year"]].head(20)

                        state  year
56260  Dadra and Nagar Haveli  1998
56261  Dadra and Nagar Haveli  1998
56262  Dadra and Nagar Haveli  1998
56263  Dadra and Nagar Haveli  1998
56264  Dadra and Nagar Haveli  1998
56265  Dadra and Nagar Haveli  1998
56266  Dadra and Nagar Haveli  1998
56267  Dadra and Nagar Haveli  1998
56268  Dadra and Nagar Haveli  1998
56269  Dadra and Nagar Haveli  1998
56270  Dadra and Nagar Haveli  1998
56271  Dadra and Nagar Haveli  1998
56272  Dadra and Nagar Haveli  1998
56273  Dadra and Nagar Haveli  1998
56274  Dadra and Nagar Haveli  1998
56275  Dadra and Nagar Haveli  1998
56276  Dadra and Nagar Haveli  1998
56277  Dadra and Nagar Haveli  1998
56278  Dadra and Nagar Haveli  1998
56279  Dadra and Nagar Haveli  1998

In [33]:
missing_pairs = df[df["rainfall"].isna()][["state", "year"]].drop_duplicates()
print(len(missing_pairs))
print(missing_pairs.head(30))

34
                         state  year
56260   Dadra and Nagar Haveli  1998
56281   Dadra and Nagar Haveli  1999
56299   Dadra and Nagar Haveli  2000
56317   Dadra and Nagar Haveli  2001
56334   Dadra and Nagar Haveli  2002
56351   Dadra and Nagar Haveli  2003
56368   Dadra and Nagar Haveli  2004
56387   Dadra and Nagar Haveli  2005
56406   Dadra and Nagar Haveli  2006
56425   Dadra and Nagar Haveli  2007
56434   Dadra and Nagar Haveli  2008
56443   Dadra and Nagar Haveli  2009
56452   Dadra and Nagar Haveli  2010
56471   Dadra and Nagar Haveli  2011
56489   Dadra and Nagar Haveli  2012
56507   Dadra and Nagar Haveli  2013
56515   Dadra and Nagar Haveli  2014
157686              Puducherry  1998
157694              Puducherry  1999
157710              Puducherry  2000
157726              Puducherry  2001
157737              Puducherry  2002
157747              Puducherry  2003
157759              Puducherry  2004
157772              Puducherry  2005
157784              Puducherry  2006
157792              Puducherry  2007
157807              Puducherry  2008
157821              Puducherry  2009
157835              Puducherry  2010

In [34]:
rainfall["state"].unique()

<StringArray>
['Andaman and Nicobar Islands',              'Andhra Pradesh',
           'Arunachal Pradesh',                       'Assam',
                   'Meghalaya',                       'Bihar',
                'Chhattisgarh',                         'Goa',
                     'Gujarat',                     'Haryana',
                  'Chandigarh',            'Himachal Pradesh',
           'Jammu and Kashmir',                   'Jharkhand',
                   'Karnataka',                      'Kerala',
              'Madhya Pradesh',                 'Maharashtra',
                     'Manipur',                     'Mizoram',
                    'Nagaland',                     'Tripura',
                      'Odisha',                      'Punjab',
                   'Rajasthan',                      'Sikkim',
                  'Tamil Nadu',                   'Telangana',
               'Uttar Pradesh',                 'Uttarakhand',
                 'West Bengal']
Length: 31, dtype: str

In [35]:
valid_states = rainfall["state"].unique()
df = df[df["state"].isin(valid_states)]

In [36]:
df = pd.merge(
    crop,
    rainfall,
    on=["state", "year"],
    how="left"
)

In [37]:
df = df.dropna(subset=["rainfall"])

In [38]:
df = df[df["state"].isin(rainfall["state"].unique())]

In [39]:
missing_pairs = df[df["rainfall"].isna()][["state", "year"]].drop_duplicates()
print(missing_pairs)

Empty DataFrame
Columns: [state, year]
Index: []

In [40]:
df["rainfall"].isna().sum()

np.int64(0)

In [41]:
df["yield"] = df["Production"] / df["Area"]

In [42]:
df = df.drop(columns=["Production"])

In [45]:
from sklearn.preprocessing import LabelEncoder

le_state = LabelEncoder()
le_crop = LabelEncoder()
le_season = LabelEncoder()

df["state"] = le_state.fit_transform(df["state"])
df["Crop"] = le_crop.fit_transform(df["Crop"])
df["Season"] = le_season.fit_transform(df["Season"])

In [46]:
x = df[["state", "year", "Season", "Crop", "Area", "rainfall"]]
y = df["yield"]

In [48]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [50]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [51]:
from sklearn.metrics import r2_score, mean_absolute_error

pred = model.predict(x_test)

print("R2 Score:", r2_score(y_test, pred))
print("MAE:", mean_absolute_error(y_test, pred))

R2 Score: 0.833583573660746
MAE: 11.394139166073302

In [53]:
import pandas as pd

importance = pd.DataFrame({
    "feature": x.columns,
    "importance": model.feature_importances_
}).sort_values(by="importance", ascending=False)

print(importance)

    feature  importance
5  rainfall    0.489097
3      Crop    0.183106
1      year    0.151813
0     state    0.090719
4      Area    0.076504
2    Season    0.008761

In [54]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6
)

In [55]:
from sklearn.metrics import r2_score, mean_absolute_error
import pickle

In [56]:
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [58]:
y_pred = model.predict(x_test)

In [59]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

In [61]:
print("R2 Score: ", r2)
print("MAE:", mae)

R2 Score:  0.8923134385195007
MAE: 16.058955155668116

In [63]:
with open("xgb_crop_yield_model.pkl", "wb") as file:
    pickle.dump(model, file)
    print("XGBoost model saved succesfully")

XGBoost model saved succesfully